<html>

  <head>
    <title>Tee - Login</title>
  </head>

  <body>
    <h1>Login</h1>

    <?php
    if (isset($message)) {
      echo "<h3>$message</h3>";
    }
    ?>

    <form method="post">
      Username <input type="text" name="username" value="" placeholder="username"><br>
      Password <input type="password" name="password" value="" placeholder="********"><br>
      <input type="hidden" name="to" value="<?php echo $to?>">
      <input type="submit" name="send" value="Send">
    </form>
  </body>
</html>
